module.exports = {
  // Screen titles and Drwer title
  titleHome: "titleHome",
  titleBePremium: "titleBePremium",
  titleRateUs: "titleRateUs",
  titleShareApp: "titleShareApp",
  titleShareAndEarn: "titleShareAndEarn",
  titleReportIssue: "titleReportIssue",
  titleAccount: "titleAccount",
  titleFavourite: "titleFavourite",
  titleDesign: "titleDesign",
  titleCart: "titleCart",
  titleNotification: "titleNotification",
  titleProfile: "titleProfile",
  titlePostProfile: "titlePostProfile",
  titlePackage: "titlePackage",
  titleWhatsAppUpdates: "titleWhatsAppUpdates",
  titReferandEarn: "titReferandEarn",
  titLegal: "titLegal",
  titSignOut: "titSignOut",
  titSignIn: "titSignIn",
  titMadeWithLoveInIndia: "titMadeWithLoveInIndia",
  titleAddReffercode: "titleAddReffercode",
  free: "free",

  // user Profile
  labUser: "labUser",
  labDob: "labDob",
  labAvDate: "labAvDate",
  labState: "labState",
  labCity: "labCity",
  labProfileImageSize: "labProfileImageSize",

  // user screen
  labMobile: "labMobile",
  labPassword: "labPassword",
  newPass: "newPass",
  reTypePass: "reTypePass",
  labSendOTP: "labSendOTP",
  labVarifyOTP: "labVarifyOTP",
  labAnOtpSent: "labAnOtpSent",
  labConfirmPassword: "labConfirmPassword",
  labReferralcode: "labReferralcode",
  labAlreadyAcc: "labAlreadyAcc",
  labNothaveAcc: "labNothaveAcc",
  labForgetPassword: "labForgetPassword",
  labForgotPass: "labForgotPass",
  labSignin: "labSignin",
  labWelcomeBack: "labWelcomeBack",
  labGetStarted: "labGetStarted",
  labSignup: "labSignup",
  labSignInWithGoogle: "labSignInWithGoogle",
  labSignInWithApple: "labSignInWithApple",
  labSignInWithFacebook: "labSignInWithFacebook",
  txtWelcome: "txtWelcome",
  txtCreateAccount: "txtCreateAccount",
  labUploadingImage: "labUploadingImage",
  labsSaving: "labsSaving",
  LayoutColor: "LayoutColor",
  FontColor: "FontColor",

  // error validator messages
  errorMobileNo: "errorMobileNo",
  errorEmail: "errorEmail",
  errorPassword: "errorPassword",
  errorConfirmPassword: "errorConfirmPassword",
  errorreTypePass: "errorreTypePass",
  errorName: "errorName",
  errorGender: "errorGender",

  // Home ItemSubCategory screen
  labAll: "labAll",
  labNoDesignAvailable: "labNoDesignAvailable",
  labNoPkgAvailable: "labNoPkgAvailable",

  //Design Screen
  labFollowUs: "labFollowUs",
  msgSocialIconLimit: "msgSocialIconLimit",
  txtShare: "txtShare",
  txtDownload: "txtDownload",
  txtEdit: "txtEdit",
  txtProfile: "txtProfile",
  txtNext: "txtNext",
  txtReset: "txtReset",
  txtBack: "txtBack",
  msgPerchasePkg: "msgPerchasePkg",
  msgPkgPurchaseSucess: "msgPkgPurchaseSucess",
  msgCreateAcc: "msgCreateAcc",
  msgCreateAccForPKg: "msgCreateAccForPKg",
  msgCreateAccEdit: "msgCreateAccEdit",
  msgDesignDownload: "msgDesignDownload",
  msgShareNotAvaillable: "msgShareNotAvaillable",
  msgSelectLayout: "msgSelectLayout",

  //UserPackage Screen
  txtDesignCredit: "txtDesignCredit",
  txtRemainingCredit: "txtRemainingCredit",
  txtPerchsedAt: "txtPerchsedAt",
  txtExpiredAtFree: "txtExpiredAtFree",
  txtExpiredAt: "txtExpiredAt",

  //UserProfile Screen
  msgCameraRollPermission: "msgCameraRollPermission",
  labUserName: "labUserName",
  labEmail: "labEmail",
  labDesignation: "labDesignation",
  labSocialMediaId: "labSocialMediaId",
  labWebsite: "labWebsite",
  txtSave: "txtSave",
  genRefCode: "genRefCode",
  errUserName: "errUserName",

  personalUserNameErr: "personalUserNameErr",
  personalMobileErr: "personalMobileErr",
  personalEmailErr: "personalEmailErr",
  personalDesignationErr: "personalDesignationErr",
  personalSocialMediaIdErr: "personalSocialMediaIdErr",
  personalWebsiteErr: "personalWebsiteErr",
  txtUploadPhotoHere: "txtUploadPhotoHere",
  txtUploadPNG: "txtUploadPNG",
  txtPhotoSize: "txtPhotoSize",
  txtLogoSize: "txtLogoSize",

  //BusinessProfile Screen
  labCompanyName: "labCompanyName",
  labAddress: "labAddress",
  errCompanyName: "errCompanyName",

  bussinessUserNameErr: "bussinessUserNameErr",
  bussinessMobileErr: "bussinessMobileErr",
  bussinessEmailErr: "bussinessEmailErr",
  bussinessAddressErr: "bussinessAddressErr",
  bussinessSocialMediaIdErr: "bussinessSocialMediaIdErr",
  bussinessWebsiteErr: "bussinessWebsiteErr",
  txtUploadLogoHere: "txtUploadLogoHere",

  // Packages Screen
  labPerchase: "labPerchase",
  labPerchaseFree: "labPerchaseFree",

  // userPackage.js

  labActive: "labActive",
  labExpired: "labExpired",

  // modal text
  modalTxtPlaceHolder: "modalTxtPlaceHolder",
  labEnterMobile: "labEnterMobile",
  modalRefferCode: "modalRefferCode",
  labSelecteLang: "labSelecteLang",
  labClose: "labClose",
  labSubmit: "labSubmit",
  labUpdate: "labUpdate",
  labSubmitSucess: "labSubmitSucess",
  labEdit: "labEdit",
  labPurchase: "labPurchase",
  labPurchasePremiumPkg: "labPurchasePremiumPkg",
  labFreeDesignLimitOver: "labFreeDesignLimitOver",
  labDownloadMoreImage: "labDownloadMoreImage",
  labFree: "labFree",
  labPackage: "labPackage",
  labPremium: "labPremium",
  labWhatsApp: "labWhatsApp",
  labUpdateWhatsApp: "labUpdateWhatsApp",
  labStayonWp: "labStayonWp",
  labUnsubscribeNoti: "labUnsubscribeNoti",
  shareYourExperiance: "shareYourExperiance",
  weLoveToHearFromYou: "weLoveToHearFromYou",
  IloveIt: "IloveIt",
  itNeedsToBeImproved: "itNeedsToBeImproved",
  labWatchAds: "labWatchAds",

  // signin
  labLoading: "labLoading",
  //
  titPersonalProfile: "titPersonalProfile",
  titBussinessProfile: "titBussinessProfile",

  // package screen
  labfreeFeature: "labfreeFeature",
  labPremiumFeature: "labPremiumFeature",
  labDescription: "labDescription",

  //
  labInStock: "labInStock",
  labOutOfStock: "labOutOfStock",

  // select language
  titSetLanguage: "titSetLanguage",
  titSelectPreferdLanguage: "titSelectPreferdLanguage",

  // otp screen
  labOtpVarification: "labOtpVarification",
  labEnterOtp: "labEnterOtp",
  labDidnotReciveOtp: "labDidnotReciveOtp",
  labResend: "labResend",

  // notification
  labNew: "labNew",
  labToday: "labToday",
  labEarl: "labEarl",
  lab1pkg: "lab1pkg",
  lab1pkgAndroid: "lab1pkgAndroid",
  lab2pkg: "lab2pkg",

  // layout popup messages
  nolayout: "nolayout",
  nolayoutBussiness: "nolayoutBussiness",
  adDesc: "adDesc",
  Freeforever: "Free forever",
  personalLay1Msg: "personalLay1Msg",
  personalLay2Msg: "personalLay2Msg",
  personalLay3Msg: "personalLay3Msg",
  personalLay4Msg: "personalLay4Msg",
  personalLay5Msg: "personalLay5Msg",
  personalLay6Msg: "personalLay6Msg",
  personalLay7Msg: "personalLay7Msg",
  personalLay8Msg: "personalLay8Msg",

  labLayouts: "labLayouts",
  labPatch: "labPatch",
  labColorCodeList: "labColorCodeList",
  labSocialMediaIcons: "labSocialMediaIcons",
  // bussiness
  businessLay1Msg: "businessLay1Msg",
  businessLay2Msg: "businessLay2Msg",
  businessLay3Msg: "businessLay3Msg",
  businessLay4Msg: "businessLay4Msg",
  businessLay5Msg: "businessLay5Msg",
  businessLay6Msg: "businessLay6Msg",
  businessLay7Msg: "businessLay7Msg",
  businessLay8Msg: "businessLay8Msg",
  businessLay9Msg: "businessLay9Msg",
  businessLay10Msg: "businessLay10Msg",
  businessLay11Msg: "businessLay11Msg",
};
